class ids_tjs:
    OCULTAR_FILTROS_TJS_COLLAPSE = "ocultar-filtros-tjs-collapse"
    OCULTAR_FILTROS_TJS_BUTTON = "ocultar-filtros-tjs-button"

    TRIBUNAL_TJS_DROPDOWN = "tribunal-tjs-dropdown"
    SELECT_ALL_TRIBUNAIS_TJS_BUTTON = "select-all-tribunais-tjs-button"
    RUBRICA_TJS_DROPDOWN = "rubrica-tjs-dropdown"
    SELECT_ALL_RUBRICAS_TJS_BUTTON = "select-all-rubricas-tjs-button"
    DECISAO_TJS_DROPDOWN = "decisao-tjs-dropdown"
    SELECT_ALL_DECISOES_TJS_BUTTON = "select-all-decisoes-tjs-button"
    PROPOSITURA_TJS_SLIDER = "propositura-tjs-slider"
    JULGAMENTO_TJS_SLIDER = "julgamento-tjs-slider"

    CONTAINER_ESTADOS_TJ = "container-estados-tj"
    CONTAINER_RUBRICAS_TJ = "container-rubricas-tj"
    CONTAINER_DECISOES_TJ = "container-decisoes-tj"
    CONTAINER_JULGAMENTO_TJ = "container-julgamento-tj"
    CONTAINER_PROPOSITURA_TJ = "container-propositura-tj"
    CONTAINER_DURACAO_TJ = "container-duracao-tj"

    ESTADOS_BUBBLE_MAP = "estados-bubble-map"
    RUBRICA_TJS_PIE_CHART = "rubrica-tjs-pie-chart"
    DECISOES_TJS_PIE_CHART = "decisoes-tjs-pie-chart"
    JULGAMENTO_TJS_BAR_CHART = "julgamento-tjs-bar-chart"
    PROPOSITURA_TJS_BAR_CHART = "propositura-tjs-bar-chart"
    DURACAO_TJS_GAUGE_CHART = "duracao-tjs-gauge-chart"

class ids_stj:
    OCULTAR_FILTROS_STJ_COLLAPSE = "ocultar-filtros-stj-collapse"
    OCULTAR_FILTROS_STJ_BUTTON = "ocultar-filtros-stj-button"

    TRIBUNAL_STJ_DROPDOWN = "tribunal-stj-dropdown"
    SELECT_ALL_TRIBUNAIS_STJ_BUTTON = "select-all-tribunais-stj-button"
    RUBRICA_STJ_DROPDOWN = "rubrica-stj-dropdown"
    SELECT_ALL_RUBRICAS_STJ_BUTTON = "select-all-rubricas-stj-button"
    CAMARA_STJ_DROPDOWN = "camara-stj-dropdown"
    SELECT_ALL_CAMARAS_STJ_BUTTON = "select-all-camaras-stj-button"
    ACAO_STJ_DROPDOWN = "acao-stj-dropdown"
    SELECT_ALL_ACOES_STJ_BUTTON = "select-all-acoes-stj-button"
    JULGAMENTO_STJ_SLIDER = "julgamento_stj_slider"

    CONTAINER_RUBRICA_STJ = "container-rubrica-stj"
    CONTAINER_CAMARA_STJ = "container-camara-stj"
    CONTAINER_ACAO_STJ = "container-acao-stj"
    CONTAINER_JULGAMENTO_STJ = "container-julgamento-stj"

    RUBRICA_STJ_PIE_CHART = "rubrica-stj-pie-chart"
    CAMARA_STJ_PIE_CHART = "camara-stj-pie-chart"
    JULGAMENTO_STJ_BAR_CHART = "julgamento-stj-bar-chart"
    ACAO_STJ_BAR_CHART = "acao-stj-bar-chart"

class ids_rubrica:
    OCULTAR_FILTROS_RUBRICA_COLLAPSE = "ocultar-filtros-rubrica-collapse"
    OCULTAR_FILTROS_RUBRICA_BUTTON = "ocultar-filtros-rubrica-button"

    TRIBUNAL_RUBRICA_DROPDOWN = "tribunal-rubrica-dropdown"
    SELECT_ALL_TRIBUNAIS_RUBRICA_BUTTON = "select-all-tribunais-rubrica-button"
    RUBRICA_DROPDOWN = "rubrica-dropdown"
    SELECT_ALL_RUBRICAS_BUTTON = "select-all-rubricas-button"
    DECISAO_RUBRICA_DROPDOWN = "decisao-rubrica-dropdown"
    SELECT_ALL_DECISOES_BUTTON = "select-all-decisoes-button"
    ATIVO_RUBRICA_DROPDOWN = "ativo-rubrica-dropdown"
    SELECT_ALL_ATIVOS_BUTTON = "select-all-ativos-button"
    PASSIVO_RUBRICA_DROPDOWN = "passivo-rubrica-dropdown"
    SELECT_ALL_PASSIVOS_BUTTON = "select-all-passivos-button"
    PROPOSITURA_RUBRICA_SLIDER = "propositura-rubrica-slider"
    JULGAMENTO_RUBRICA_SLIDER = "julgamento-rubrica-slider"

    CONTAINER_DURACAO_RUBRICA = "container-duracao-rubrica"
    CONTAINER_DECISOES_RUBRICA = "container-decisoes-rubrica"
    CONTAINER_ATIVO_RUBRICA = "container-ativo-rubrica"
    CONTAINER_PASSIVO_RUBRICA = "container-passivo-rubrica"
    CONTAINER_PROPOSITURA_RUBRICA = "container-propositura-rubrica"
    CONTAINER_JULGAMENTO_RUBRICA = "container-julgamento-rubrica"

    DURACAO_RUBRICA_GAUGE_CHART = "duracao-rubrica-gauge-chart"
    DECISOES_RUBRICA_PIE_CHART = "decisoes-rubrica-pie-chart"
    ATIVO_RUBRICA_PIE_CHART = "ativo-rubrica-pie-chart"
    PASSIVO_RUBRICA_PIE_CHART = "passivo-rubrica-pie-chart"
    PROPOSITURA_RUBRICA_BAR_CHART = "propositura-rubrica-bar-chart"
    JULGAMENTO_RUBRICA_BAR_CHART = "julgamento-rubrica-bar-chart"